# ============================================================================
# Name: Heiko Schäfer (TUXPLAYER)
# Datum: 23. Februar 2026, 06:05
# Beschreibung: GitHub Action zur automatischen Aktualisierung des README
# Zweck: Präsentiert Besuchern die neuesten Inhalte von tuxhs.de
# ============================================================================
name: Aktuelle Blogbeiträge - Arbeitslauf
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: README mit Blogbeiträgen aktualisieren
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Musikpfosten ziehen
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST-MUSIC"
          feed_list: "https://tuxhs.de/feed/?cat=musik"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          max_post_count: 5
      - name: Pull-Code-Pfosten
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST-CODE"
          feed_list: "https://tuxhs.de/feed/"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          max_post_count: 5
